# Generated by Django 5.2.14 on 2026-05-28 13:20

import django.db.models.deletion
import gestion_classes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la classe')),
                ('matiere', models.CharField(max_length=100, verbose_name='Matière')),
                ('annee_scolaire', models.CharField(max_length=9, verbose_name='Année scolaire')),
                ('code_invitation', models.CharField(default=gestion_classes.models.generer_code_invitation, max_length=6, unique=True, verbose_name='Code invitation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
