# Generated by Django 5.2.14 on 2026-06-12 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_classes', '0002_inscription_archivage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='is_archived',
            new_name='archivee',
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='annee_scolaire',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='gestion_classes.classe'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='eleve',
            field=models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
