# Generated by Django 5.2.14 on 2026-06-12 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_classes', '0003_rename_is_archived_classe_archivee_classe_niveau_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='archivee',
            new_name='is_archived',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='niveau',
        ),
        migrations.AlterField(
            model_name='classe',
            name='annee_scolaire',
            field=models.CharField(max_length=9, verbose_name='Année scolaire'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='gestion_classes.classe', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='eleve',
            field=models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Élève'),
        ),
    ]
